services:
  zerotier:
    container_name: zerotier
    image: zerotier/zerotier:1.14.0
    restart: unless-stopped
    command: "${NETWORK_ID}"
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun
    network_mode: host
